language: node_js
node_js:
    - 7
    - 8
    - 9
    - 10
    - 11

cache:
    npm: true
    directories:
        - node_modules

script:
    - npm run buid
    - npm run lint
    - npm run test
    - npm run coverage

after_success:
    - npm global add coveralls && npm run coverage:report | coveralls

deploy:
    provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_TOKEN
    on:
        tags: true
        node: 10
