language: node_js
node_js:
    - 4
    - 6
    - 7
    - 8
cache:
  directories:
    - node_modules
before_install:
  - test ! -d node_modules || npm prune
  - test ! -d node_modules || npm rebuild
script:
    - yarn lint
    - yarn test
    - yarn coverage
after_script: yarn add coveralls && yarn coverage:report | coveralls
