language: node_js
node_js:
    - 7
    - 8

cache:
    yarn: true
    directories:
        - node_modules

script:
    - yarn lint
    - yarn test

after_success:
    - yarn global add coveralls && yarn coverage | coveralls

deploy:
    provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_TOKEN
    on:
        tags: true
        node: 8
