language: node_js
node_js:
    - '7.6'
    - '7.7'
    - '7.8'
    - '7.9'
    - '7.10'
    - '8.0'
    - '8.1'
cache:
  directories:
    - node_modules
script:
    - yarn lint
    - yarn test
after_script: yarn add coveralls && yarn coverage | coveralls
